---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  labels:
    tier: infrastructure
    environment: development
data:
  mongo-user: root
  mongo-password: notsafe

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
  labels:
    tier: infrastructure
    environment: development
data:
  mosquitto.conf: |
    allow_anonymous true
    listener 1883