apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-deployment
  labels:
    app: mqtt
    tier: infrastructure
    environment: development
spec:
  replicas: 1
  template:
    metadata:
      name: mqtt-deployment
      labels:
        app: mqtt
    spec:
      containers:
        - name: mqtt-service
          image: eclipse-mosquitto
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1883
              hostPort: 1883
          volumeMounts:
            - mountPath: "/mosquitto/config/mosquitto.conf"
              subPath: mosquitto.conf
              name: mosquitto-config
      volumes:
        - name: mosquitto-config
          configMap:
            name: mqtt-config
      restartPolicy: Always
  selector:
    matchLabels:
      app: mqtt

---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
spec:
  selector:
    app: mqtt
  ports:
    - port: 1883
      protocol: TCP
      targetPort: 1883
      nodePort: 32002
  type: NodePort