name: Pull Request

on:
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18

      - name: Cache goLang files
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ github.head_ref || github.ref_name }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ github.head_ref || github.ref_name }}-golang-

      - name: Setup Minikube
        uses: medyagh/setup-minikube@master

      - name: Test
        run: go test -v -coverprofile=coverage.out ./

      - name: Scan Code
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
