name: Vet

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Cache goLang files
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ github.head_ref || github.ref_name }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ github.head_ref || github.ref_name }}-golang-

      - name: Vet
        run: go vet

      - name: Test
        run: go test